name: 'Build'
on:
  push:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-13, ubuntu-22.04, windows-2022]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies (Windows)
        if: matrix.platform == 'windows-2022'
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          choco install git msys2 visualstudio2022-workload-vctools python
          python -m pip install --user pipx
          python -m pipx ensurepath
          pipx install gvsbuild
          gvsbuild build gtk4
          $env:Path = "C:\gtk-build\gtk\x64\release\bin;" + $env:Path
      - name: Install dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Install dependencies (macOS)
        if: matrix.platform == 'macos-13'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install gtk4
      - name: Compile software
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload the Linux packages
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'ubuntu-22.04'
        with:
          name: linux-packages
          path: target/release/quiclime-client
      - name: Upload the macOS packages
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'macos-13'
        with:
          name: macos-packages
          path: target/release/quiclime-client
      - name: Upload the Windows packages
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'windows-2022'
        with:
          name: windows-packages
          path: target/release/quiclime-client.exe
