name: 'Build'
on:
  push:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-13, ubuntu-22.04, windows-2022]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies (Windows)
        if: matrix.platform == 'windows-2022'
        run: |
          irm get.scoop.sh | iex
          scoop install vcpkg pkg-config
          vcpkg install gtk4
          vcpkg integrate install
      - name: Install dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-4-dev build-essential
      - name: Install dependencies (macOS)
        if: matrix.platform == 'macos-13'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install gtk4
      - name: Compile software
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload the Linux packages
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'ubuntu-22.04'
        with:
          name: linux-packages
          path: target/release/quiclime-client
      - name: Upload the macOS packages
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'macos-13'
        with:
          name: macos-packages
          path: target/release/quiclime-client
      - name: Upload the Windows packages
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'windows-2022'
        with:
          name: windows-packages
          path: target/release/quiclime-client.exe
